"""empty message

Revision ID: acb791d085b9
Revises: 
Create Date: 2021-01-18 08:57:14.892529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acb791d085b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients_changed_medicine', sa.Column('newPatientDescription', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients_changed_medicine', 'newPatientDescription')
    # ### end Alembic commands ###
